[GERAL]
VERSION=1.0
NOME_AUTOR="Pablo Veinberg"
EMAIL_AUTOR="psebastianv@minsait.com"
DATE="$(date --date="-0 day" "+%Y%m%d")"
DATETIME="$(date --date="-0 day" "+%Y-%m-%d %H:%M:%S")"

[BASE]
BASE_DIR=~/dev/indra/formacao-engenharia-dados-desafio
HQL_DIR=scripts/hql
LOG_DIR=logs
RUN_DIR=run
APP_DIR=app

[REMOTE]
SOURCE_REMOTE_BASE=https://raw.githubusercontent.com/pveinberg/project_data/refs/heads/main/vendas
REMOTE_FILES=("CLIENTES.csv" "DIVISAO.csv" "ENDERECO.csv" "REGIAO.csv" "VENDAS.csv")

[LOCAL]
LOCAL_EDGE_TEMP=~/dev/indra/formacao-dev-bigdata/bigdata_docker/share/data/raw
LOCAL_DIR_RAW=/dataset/raw
LOCAL_DIR_GOLD=0

[HDFS]
HDFS_EDGE_TEMP=/share/data/raw
HDFS_DIR_RAW=/datalake/raw
HDFS_DIR_GOLD=/datalake/gold
DOCKER_HDFS_ID=datanode

[HIVE]
# Database
TARGET_STAGE_DATABASE="stg_vendas_2024_db"
TARGET_PRD_DATABASE="prd_vendas_2024_db"
DOCKER_HIVE_ID=hive-server